### ISSUE TITLE
Fix bbc and lenta parser

### ISSUE THREAD

**Issue by drewxa** [drewxa/canyouseeit#1]
Исправить fix get_content_from_bbc_russian и get_content_from_lenta, чтобы методы возвращали строку со статьёй в кириллице

**Comment by Rockstar18** [comment]
в таком же виде текст получается с mk.ru и Ведомости

**Comment by Rockstar18** [comment]
еще и LifeNews

**Comment by drewxa** [comment]
вроде чиниться, если открывать через 
``` python 
urllib2.urlopen(article_url).read().decode('utf-8')
```
подробнее можно глянуть 5615785aff5ce283d61b9e1e6a7c9e8f85e6b9f5

**Comment by drewxa** [comment]
решение нашел тут http://webnewage.org/2009/11/04/be-ware-lxml-html/
