### ISSUE TITLE
Добавить поле tags

### ISSUE THREAD

**Issue by drewxa** [drewxa/canyouseeit#2]
В некоторых статьях, например в http://ria.ru/society/20151002/1295449183.html, есть список с тэгами. Их все надо записывать в поле tags. Сохранять структуру "Организации", "Места" и др. не надо. При налиции тэгов в других источниках делать тоже самое

**Comment by Rockstar18** [comment]
У каждого rss_object есть возможность получить список тегов, единственно там более общие теги , посмотрите может таких хватит ?

**Comment by drewxa** [comment]
Глянул у парочки статей, кажется, что и их хватит

**Comment by Rockstar18** [comment]
как оказалось не у каждого издания есть теги в rss итемах + там обычно только один тег и сохраняет в странном виде (типо универсальная функция) , в общем сделал отдельные функции для сайтов , на которых есть теги
