### ISSUE TITLE
Структура проекта

### ISSUE THREAD

**Issue by drewxa** [drewxa/canyouseeit#8]
Тут обсуждается структура проектов, формат хранимых данных, как и когда получать новые данные и др.

**Comment by drewxa** [comment]
Поменял структуру. Выбор сделан в пользу ООП (что логично). Отказался от процедурного программирования (изначально ошибочное проектирование привело к излишним усложнениям).
```python
class BaseParser:
    # конструктор
    def __init__(self, rss_url, max_news=2):

    # эту функцию надо переопределить для корректного получения содержания статьи
    def get_content(self):

    # эту функцию надо переопределить для корректного получения тэгов статьи
    def get_tags(self):

    # эта функция вызывает get_tags и get_content для получения всех данных
    # не требует переопределения в дочерних классах
    def get_news(self, timestamp=None):
```
В файле `derived_site_parsers.py` все дочерние классы для сайтов.

Есть желание сохранять всю статью в отдельном файле, а в поле `content` хранить относительный путь до файла.

**Comment by drewxa** [comment]
Вынес сохранение данных в `save_to_file`. Теперь поле *content* содержит относительный путь до файла с содержимым статьи. Так сделано, чтобы всю техническую информацию хранить в маленьком файле, а текст статей в отдельной папке. Это позволить проводить анализ технической информации без ресурсоемкой загрузки текста.

**Comment by drewxa** [comment]
Сохраняем время публикации в виде UNIX timestamp. Так удобнее анализировать

**Comment by Rockstar18** [comment]
Так как есть необходимость получать данные из соцсетей
предлагаю сделать базовый класс выше уровнем и от него наследовать два базовых класса для сайтов и соцсетей ( так же можно будет сделать любые другие базовые классы для новых источников)
![uml1](https://cloud.githubusercontent.com/assets/5003472/12004282/3b4eed76-ab66-11e5-828a-dbe6a9b695ca.jpg)

**Comment by drewxa** [comment]
да, с точки зрения проектирования это верное решение.

**Comment by Rockstar18** [comment]
от SocialProvider будут наследованы базовые классы для каждой социальной сети
