### ISSUE TITLE
Неудобные сайты с неудобной структурой статьи

### ISSUE THREAD

**Issue by Rockstar18** [drewxa/canyouseeit#9]
Некоторые новостные сайты выдают текст таким образом что в тегах <p> есть еще вложенные теги , которые вместе с их родителем <p> хаотично делят текст на куски (причем текст в самом родительском теге <p> может находиться где угодно : перед , после , между дочерними тегами) , иногда даже отделяя одну букву от слова. Так вот что с ними делать , может есть какая то функция которая позволяет такое парсить ? ну или можно забирать новости у них из группы в социальной сети если такая есть и если там есть полный текст статьи.

**Comment by drewxa** [comment]
Что за сайты такие, пару примеров можно?

**Comment by Rockstar18** [comment]
http://www.forbes.ru/news/309053-vlasti-moskvy-poobeshchali-ne-shtrafovat-za-neoplachennuyu-parkovku-iz-za-sboya , вот например, а так на форбс есть еще такие же. Видел на lifenews еще такие штуки.

**Comment by drewxa** [comment]
если я правильно понял в чем проблема, то можно попробовать следующее
```python
import lxml.html as html

print html.tostring(some_html_node, method='text', encoding='utf8')
```

**Comment by drewxa** [comment]
еще можно для парсинга html перейти на библиотеку `beautifulsoup`. Но на первый взгляд она мне показалась не очень дружелюбной

**Comment by Rockstar18** [comment]
print html.tostring(some_html_node, method='text', encoding='utf8') , да это скорее всего поможет , хорошая штука, спасибо . Еще заметил что не получается загружать https страницы. Выдает такую ошибку 
IOError: Error reading file 'https://slon.ru/posts/61667?utm_source=slon.ru&utm_medium=rss&utm_campaign=fast': failed to load external entity "https://slon.ru/posts/61667?utm_source=slon.ru&utm_medium=rss&utm_campaign=fast"

**Comment by drewxa** [comment]
вроде должно сработать
```python
from urllib2 import urlopen
import lxml.html as html

article_page = html.parse(urlopen(url_to_html_document))
```

**Comment by Rockstar18** [comment]
print html.tostring(some_html_node, method='text', encoding='utf8')
не везде работает utf8 (точнее пока вообще нигде) , получается если использовать unicode вместо utf8
